version: "3.8"
services:
  web:
    restart: always
    build: .
    command: python3 app.py
    volumes:
      - ".:/ICT3102_Proj"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    mem_limit: 512m
    mem_reservation: 256M
    cpus: 1