version: "3.8"
services:
  web:
    restart: always
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
      - ".:/ICT3102_Proj"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    mem_limit: 512m
    mem_reservation: 256M
    cpus: 1