version: "3.8"
services:
  web:
    restart: always
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
      - ".:/ICT3102_Proj_old"
    ports:
      - "5001:5001"
    expose:
      - "5001"
    mem_limit: 512m
    mem_reservation: 256M
    cpus: 1